# Generated by Django 4.1.1 on 2022-09-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.IntegerField(primary_key=True, serialize=False)),
                ('coach_type', models.CharField(default='sleeper', max_length=10)),
                ('avail_no_of_seats', models.IntegerField()),
            ],
        ),
    ]
