# Generated by Django 4.1.1 on 2022-09-13 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('WL', 'Waiting list'), ('CNF', 'Confirm'), ('RAC', 'RAC')], max_length=3)),
                ('no_of_passengers', models.IntegerField()),
                ('berth_no', models.IntegerField()),
                ('coach_type', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='home.coach')),
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.train')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
