# Generated by Django 4.1.1 on 2022-09-13 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=50)),
                ('hault', models.IntegerField()),
                ('arrival_time', models.TimeField()),
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.train')),
            ],
        ),
    ]
