# Generated by Django 4.1.1 on 2022-09-13 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_seat1', models.IntegerField()),
                ('b_seat2', models.IntegerField()),
                ('w_seat1', models.IntegerField()),
                ('w_seat2', models.IntegerField()),
                ('a_seat1', models.IntegerField()),
                ('a_seat2', models.IntegerField()),
                ('fair2', models.IntegerField()),
                ('train_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.train')),
            ],
        ),
    ]
