# Generated by Django 4.1.1 on 2022-09-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pnr_no', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('reservation_status', models.CharField(choices=[('WL', 'Waiting list'), ('CNF', 'Confirm'), ('RAC', 'RAC')], max_length=3)),
                ('seat_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ticket')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
