# Generated by Django 4.1.1 on 2022-09-13 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_cancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_arrival', models.TimeField()),
                ('reached_time', models.TimeField()),
                ('expected_departure', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('journey_date', models.DateField()),
                ('station_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.station')),
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.train')),
            ],
        ),
    ]
