# Generated by Django 4.1.1 on 2022-09-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_trainstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='train_no',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=1),
        ),
    ]
