# Generated by Django 4.1.1 on 2022-09-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_booking_train_no_alter_user_gender'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='user',
        #     name='email',
        #     field=models.EmailField(max_length=50, unique=True),
        # ),
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
