# Generated by Django 4.1.1 on 2022-09-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_user_email_alter_user_mobile_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='User_email',
        ),
    ]
