# Generated by Django 4.1.1 on 2022-09-26 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='train_no',
        ),
        migrations.AddField(
            model_name='train',
            name='station_no',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.station'),
        ),
    ]
