# Generated by Django 4.1.1 on 2022-09-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_train_station_no_train_station_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='coach_id',
        ),
        migrations.AddField(
            model_name='train',
            name='coach_id',
            field=models.ManyToManyField(to='home.coach'),
        ),
    ]
