# Generated by Django 4.1.1 on 2022-09-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_train_coach_id_train_coach_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndDateOfJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StartDateOfJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
            ],
        ),
    ]
