# Generated by Django 4.1.1 on 2022-09-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_enddateofjourney_startdateofjourney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='station_no',
        ),
        migrations.AddField(
            model_name='train',
            name='dest',
            field=models.ForeignKey(default='', on_delete=models.SET(None), related_name='dest_tickets', to='home.station'),
        ),
        migrations.AddField(
            model_name='train',
            name='distance',
            field=models.IntegerField(null=True, verbose_name='Distance'),
        ),
        migrations.AddField(
            model_name='train',
            name='duration_h',
            field=models.IntegerField(null=True, verbose_name='Duration Hours'),
        ),
        migrations.AddField(
            model_name='train',
            name='duration_m',
            field=models.IntegerField(null=True, verbose_name='Duration Minutes'),
        ),
        migrations.AddField(
            model_name='train',
            name='source',
            field=models.ForeignKey(default='', on_delete=models.SET(None), related_name='source_tickets', to='home.station'),
        ),
    ]
