# Generated by Django 4.1.1 on 2022-09-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_train_station_no_train_dest_train_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='coach_id',
        ),
    ]
