# Generated by Django 4.1.1 on 2022-09-27 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_train_coach_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat_Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_ac', models.IntegerField(verbose_name='1st AC')),
                ('second_ac', models.IntegerField(verbose_name='2nd AC')),
                ('third_ac', models.IntegerField(verbose_name='3rd AC')),
                ('sleeper', models.IntegerField(verbose_name='Sleeper')),
                ('date', models.DateField(verbose_name='Date')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_chart', to='home.train')),
            ],
        ),
    ]
