# Generated by Django 4.1.1 on 2022-09-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_seat_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='pnr_no',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='reservation_status',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='seat_no',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=1),
        ),
    ]
