# Generated by Django 4.1.1 on 2022-09-27 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_passenger_pnr_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('arrival', models.CharField(max_length=8, null=True, verbose_name='Arrival')),
                ('day', models.IntegerField(null=True, verbose_name='Day')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('departure', models.CharField(max_length=8, null=True, verbose_name='Departure')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_schedule', to='home.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_schedule', to='home.train')),
            ],
        ),
    ]
