# Generated by Django 4.1.1 on 2022-09-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_ticket_berth_no_remove_ticket_coach_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='train',
            name='availability_of_seats',
        ),
        migrations.RemoveField(
            model_name='train',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='train',
            name='train_date',
        ),
    ]
