# Generated by Django 4.1.1 on 2022-09-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_train_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='station',
            name='hault',
        ),
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='station',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
