# Generated by Django 4.1.1 on 2022-09-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_station_arrival_time_remove_station_hault_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='source_time',
            field=models.TimeField(default='20:00'),
        ),
    ]
