# Generated by Django 4.1.1 on 2022-09-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_train_source_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='dest_time',
            field=models.TimeField(default='20:00', verbose_name='dest_time'),
        ),
        migrations.AlterField(
            model_name='train',
            name='source_time',
            field=models.TimeField(default='20:00', verbose_name='source_time'),
        ),
    ]
