# Generated by Django 4.1.1 on 2022-09-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_train_dest_time_alter_train_source_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='passenger_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
