# Generated by Django 4.1.1 on 2022-09-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_ticket_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='passenger',
        ),
        migrations.AddField(
            model_name='ticket',
            name='passenger',
            field=models.ManyToManyField(max_length=20, to='home.passenger'),
        ),
    ]
