# Generated by Django 4.1.1 on 2022-09-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_ticket_passenger_ticket_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='dest',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='dest_schedule',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='source',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='source_schedule',
        ),
    ]
