# Generated by Django 4.1.1 on 2022-09-29 10:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_ticket_dest_remove_ticket_dest_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pnr',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='pnr',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tickets_pnr', to='home.pnr'),
        ),
    ]
