# Generated by Django 4.1.1 on 2022-10-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_pnr_ticket_pnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_ans',
            field=models.CharField(default='john', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_ques',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], default='What is your pet name?', max_length=50),
        ),
    ]
