# Generated by Django 4.1.1 on 2022-10-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_user_security_ans_alter_user_security_ques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_ques',
            field=models.CharField(choices=[('What is your pet name?', 'What is your pet name?'), ('What is the name of your first school?', 'What is the name of your first school?'), ('Who is your Childhood hero?', 'Who is your Childhood hero?'), ('What is your favourite past-time?', 'What is your favourite past-time?'), ('What is your all time favourite sports team?', 'What is your all time favourite sports team?'), ('What is your fathers middle name?', 'What is your fathers middle name?'), ('Where did you first meet your spouse?', 'Where did you first meet your spouse?')], default='What is your pet name?', max_length=50),
        ),
    ]
