# Generated by Django 4.1.1 on 2022-10-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_user_security_ques'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seats',
            field=models.CharField(default='', max_length=100, verbose_name='seat'),
        ),
    ]
