# Generated by Django 4.1.1 on 2022-10-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_ticket_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='pnr',
        ),
    ]
