# Generated by Django 4.1.1 on 2022-10-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_ticket_pnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fare',
            field=models.CharField(default='', max_length=10, verbose_name='Fare'),
        ),
    ]
