# Generated by Django 4.1.1 on 2022-10-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
