# Generated by Django 4.1.1 on 2022-10-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_train_train_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
