# Generated by Django 4.1.1 on 2022-10-17 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_train_train_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancel',
            name='ticket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ticket'),
        ),
    ]
