# Generated by Django 4.1.1 on 2022-10-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_cancel_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='BOOKED', max_length=10, verbose_name='status'),
        ),
    ]
