# Generated by Django 4.1.1 on 2022-10-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancel',
            name='passenger_id',
        ),
    ]
