# Generated by Django 4.1.1 on 2022-10-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_remove_cancel_passenger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancel',
            name='ticket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ticket', unique=True),
        ),
    ]
