# Generated by Django 4.1.1 on 2022-10-27 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_cancel_ticket_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat_chart',
            unique_together={('train', 'date')},
        ),
    ]
